### ISSUE TITLE
Needs 'build' version so that other modules that depend on it can run their phantomJS tests

### ISSUE THREAD

**Issue by diasdavid** [dignifiedquire/idb-plus-blob-store#2]
I'm being unable to run the PhantomJS tests (and therefore release it) on js-ipfs-repo because this module doesn't expose an ES5 version.

https://github.com/dignifiedquire/idb-plus-blob-store/blob/master/package.json#L5

Missing `lib` version and `jsnext:main` pointing to `src`

@dignifiedquire

**Comment by dignifiedquire** [comment]
What's the error? this should be pure ES5 in src

**Comment by diasdavid** [comment]
`const` https://github.com/dignifiedquire/idb-plus-blob-store/blob/master/src/index.js#L162

**Comment by dignifiedquire** [comment]
Fixed in https://github.com/dignifiedquire/idb-plus-blob-store/commit/59b4d11d344b85c715a0bcbb5740ac575ca6adfd

**Comment by diasdavid** [comment]
Thank you :)
